#!/bin/bash
# HoneyCrypt CLI - Interactive Demo
# This shows how to use the three main commands

echo "========================================="
echo "HoneyCrypt CLI v1.0 - Usage Demo"
echo "========================================="
echo ""

echo "COMMAND 1: Standard Encryption"
echo "-------------------------------"
echo "Usage: ./honeycrypt --encrypt <real_file> <decoy_file>"
echo ""
echo "Example:"
echo "  $ ./honeycrypt --encrypt secret.txt fake.txt"
echo "  Enter password for the real file:"
echo "  Password: ******** (hidden)"
echo "  "
echo "  ✓ Encryption complete!"
echo "  ℹ Output file: secret.txt.hcrypt"
echo "  ℹ Generated decoy passwords (save these!):"
echo "  ℹ   Decoy password 1: sunshine1975"
echo "  ℹ   Decoy password 2: Cascade&911Cipher"
echo ""
echo ""

echo "COMMAND 2: Decryption"
echo "---------------------"
echo "Usage: ./honeycrypt --decrypt <file.hcrypt>"
echo ""
echo "Example:"
echo "  $ ./honeycrypt --decrypt secret.txt.hcrypt"
echo "  Enter password to decrypt:"
echo "  Password: ******** (hidden)"
echo "  "
echo "  ✓ Decryption complete!"
echo "  ℹ Output file: secret.txt_decrypted"
echo "  ℹ Type: REAL file"
echo ""
echo ""

echo "COMMAND 3: Multi-Decoy Encryption"
echo "----------------------------------"
echo "Usage: ./honeycrypt --multiencrypt <real_file>"
echo ""
echo "Example:"
echo "  $ ./honeycrypt --multiencrypt important.doc"
echo "  Enter password for the real file:"
echo "  Password: ******** (hidden)"
echo "  "
echo "  --- Decoy File 1 ---"
echo "  Enter decoy file path: decoy1.txt"
echo "  Enter password for decoy file 1:"
echo "  Password: ******** (hidden)"
echo "  Do you want to add another decoy file? (yes/no): yes"
echo "  "
echo "  --- Decoy File 2 ---"
echo "  Enter decoy file path: decoy2.pdf"
echo "  Enter password for decoy file 2:"
echo "  Password: ******** (hidden)"
echo "  Do you want to add another decoy file? (yes/no): no"
echo "  "
echo "  ✓ Multi-decoy encryption complete!"
echo "  ℹ Total files: 1 real + 2 decoys"
echo ""
echo ""

echo "========================================="
echo "Key Features"
echo "========================================="
echo "✓ Passwords are HIDDEN when you type"
echo "✓ Simple commands - just 3 to remember"
echo "✓ Interactive prompts guide you"
echo "✓ Automatic file naming (.hcrypt)"
echo "✓ Plausible deniability built-in"
echo ""

echo "For help, run: ./honeycrypt --help"
echo ""
